# Generated by Django 3.0.5 on 2020-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
