# Generated by Django 3.0.5 on 2020-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user-thumb.jpg', upload_to='profile_pics'),
        ),
    ]
